import { NextFunction, Request, Response } from 'express';
import { auditContextFromRequest } from '../../utils/audit';
import { sendCreated, sendNoContent, sendSuccess } from '../../utils/response';
import * as svc from './platform-showcases.service';
const run=(fn:(req:Request)=>Promise<unknown>,created=false)=>(req:Request,res:Response,next:NextFunction)=>{fn(req).then(x=>created?sendCreated(res,x):sendSuccess(res,x)).catch(next);};
const ctx=(r:Request)=>auditContextFromRequest(r);
export const listSections=async (r:Request,res:Response,n:NextFunction)=>{try{const x=await svc.listSections(r.query as never);sendSuccess(res,x.items,200,x.meta);}catch(err){n(err);}};
export const getSection=run(r=>svc.getSection(r.params.id));
export const createSection=run(r=>svc.createSection(r.body,ctx(r)),true);
export const updateSection=run(r=>svc.updateSection(r.params.id,r.body,ctx(r)));
export const changeSectionStatus=run(r=>svc.updateSection(r.params.id,r.body,ctx(r)));
export const reorderSections=run(r=>svc.reorderSections(r.body,ctx(r)));
export const deleteSection=(r:Request,res:Response,n:NextFunction)=>svc.deleteSection(r.params.id,ctx(r)).then(()=>sendNoContent(res)).catch(n);
export const listItems=async (r:Request,res:Response,n:NextFunction)=>{try{const x=await svc.listItems(r.query as never);sendSuccess(res,x.items,200,x.meta);}catch(err){n(err);}};
export const getItem=run(r=>svc.getItem(r.params.id));
export const createItem=run(r=>svc.createItem(r.params.sectionId,r.body,ctx(r)),true);
export const updateItem=run(r=>svc.updateItem(r.params.id,r.body,ctx(r)));
export const changeItemActive=updateItem; export const changeItemFeatured=updateItem;
export const reorderItems=run(r=>svc.reorderItems(r.body,ctx(r)));
export const deleteItem=(r:Request,res:Response,n:NextFunction)=>svc.deleteItem(r.params.id,ctx(r)).then(()=>sendNoContent(res)).catch(n);
export const createLink=run(r=>svc.createLink(r.params.itemId,r.body,ctx(r)),true);
export const updateLink=run(r=>svc.updateLink(r.params.linkId,r.body,ctx(r)));
export const changeLinkActive=updateLink;
export const reorderLinks=run(r=>svc.reorderLinks(r.body,ctx(r)));
export const deleteLink=(r:Request,res:Response,n:NextFunction)=>svc.deleteLink(r.params.linkId,ctx(r)).then(()=>sendNoContent(res)).catch(n);
