import { Router } from 'express';
import { ACTIONS, RESOURCES } from '../../config/constants';
import { authenticate } from '../../middlewares/authenticate';
import { authorize } from '../../middlewares/authorize';
import { validate } from '../../middlewares/validate';
import { validateUuid } from '../../middlewares/validateUuid';
import * as c from './platform-showcases.controller';
import { activeSchema, featuredSchema, itemListSchema, itemWriteSchema, linkWriteSchema, reorderSchema, sectionListSchema, sectionWriteSchema, statusSchema, updateItemSchema, updateLinkSchema, updateSectionSchema } from './platform-showcases.types';
export const platformShowcasesAdminRouter=Router(); platformShowcasesAdminRouter.use(authenticate);
const read=authorize(RESOURCES.APP_SHOWCASES,ACTIONS.READ), create=authorize(RESOURCES.APP_SHOWCASES,ACTIONS.CREATE), update=authorize(RESOURCES.APP_SHOWCASES,ACTIONS.UPDATE), del=authorize(RESOURCES.APP_SHOWCASES,ACTIONS.DELETE), publish=authorize(RESOURCES.APP_SHOWCASES,ACTIONS.PUBLISH);
platformShowcasesAdminRouter.get('/sections',read,validate(sectionListSchema,'query'),c.listSections);
platformShowcasesAdminRouter.post('/sections',create,validate(sectionWriteSchema),c.createSection);
platformShowcasesAdminRouter.patch('/sections/reorder',update,validate(reorderSchema),c.reorderSections);
platformShowcasesAdminRouter.get('/sections/:id',validateUuid('id'),read,c.getSection);
platformShowcasesAdminRouter.patch('/sections/:id',validateUuid('id'),update,validate(updateSectionSchema),c.updateSection);
platformShowcasesAdminRouter.patch('/sections/:id/status',validateUuid('id'),publish,validate(statusSchema),c.changeSectionStatus);
platformShowcasesAdminRouter.delete('/sections/:id',validateUuid('id'),del,c.deleteSection);
platformShowcasesAdminRouter.get('/items',read,validate(itemListSchema,'query'),c.listItems);
platformShowcasesAdminRouter.post('/sections/:sectionId/items',validateUuid('sectionId'),create,validate(itemWriteSchema),c.createItem);
platformShowcasesAdminRouter.patch('/items/reorder',update,validate(reorderSchema),c.reorderItems);
platformShowcasesAdminRouter.get('/items/:id',validateUuid('id'),read,c.getItem);
platformShowcasesAdminRouter.patch('/items/:id',validateUuid('id'),update,validate(updateItemSchema),c.updateItem);
platformShowcasesAdminRouter.patch('/items/:id/active',validateUuid('id'),update,validate(activeSchema),c.changeItemActive);
platformShowcasesAdminRouter.patch('/items/:id/featured',validateUuid('id'),update,validate(featuredSchema),c.changeItemFeatured);
platformShowcasesAdminRouter.delete('/items/:id',validateUuid('id'),del,c.deleteItem);
platformShowcasesAdminRouter.post('/items/:itemId/links',validateUuid('itemId'),create,validate(linkWriteSchema),c.createLink);
platformShowcasesAdminRouter.patch('/links/reorder',update,validate(reorderSchema),c.reorderLinks);
platformShowcasesAdminRouter.patch('/links/:linkId',validateUuid('linkId'),update,validate(updateLinkSchema),c.updateLink);
platformShowcasesAdminRouter.patch('/links/:linkId/active',validateUuid('linkId'),update,validate(activeSchema),c.changeLinkActive);
platformShowcasesAdminRouter.delete('/links/:linkId',validateUuid('linkId'),del,c.deleteLink);
