export const MASTER_SEED_MODULE_ORDER = [
  'roles-permissions',
  'admin-user',
  'site-settings',
  'locations',
  'location-nodes',
  'campaigns',
  'campaign-coverages',
  'community-membership',
  'membership-reference',
  'donations',
  'cms',
  'payments',
  'mail',
  'contact-inquiry',
  'clinic-directory',
  'campaign-faqs',
  'video-categories',
  'app-control',
  'app-control-reference',
] as const;
